name: VisionAuth CI

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies
        run: uv sync --all-groups

      - name: Ruff
        run: uv run ruff check .

      - name: Black
        run: uv run black --check .

      - name: MyPy
        run: uv run mypy app

      - name: Pytest
        run: uv run pytest
